### ISSUE TITLE
codeguru-profiler-java-agent profiler choice?

### ISSUE THREAD

**Issue by brcolow** [aws-samples/aws-codeguru-profiler-demo-application#19]
In decompiled codeguru-profiler-java-agent I see that there are two methods to use for collecting profiling data. Namely JMX and the new Java Flight Recorder Consumer API. Are both used always or is it possible to select between them? It seems that JMX requires `com.sun.management` module and in newer JDKs I am getting a `module not found` error - so being able to disable JMX and only use the `jdk.jfr.consumer` profiler would be ideal.

For reference, here is the error I am getting when trying to run codeguru-profiler-java-agent on AWS lambda with Java 14:

```
Caused by: java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean
at software.amazon.codeguruprofilerjavaagent.CpuTimeMonitor.<init>(CPUTimeMonitor.kt:7)
at software.amazon.codeguruprofilerjavaagent.CpuTimeMonitor.<init>(CPUTimeMonitor.kt)
at software.amazon.codeguruprofilerjavaagent.ProfilingCommand.<init>(ProfilingCommand.java:88)
at software.amazon.codeguruprofilerjavaagent.ProfilingCommandWithPause.<init>(ProfilingCommandWithPause.java:56)
at software.amazon.codeguruprofilerjavaagent.ProfilerWithPause.createNewProfilingCommand(ProfilerWithPause.java:251)
at software.amazon.codeguruprofilerjavaagent.ProfilerWithPause.lambda$start$0(ProfilerWithPause.java:204)
at software.amazon.codeguruprofilerjavaagent.Profiler.startWithProfilingCommand(Profiler.java:247)
at software.amazon.codeguruprofilerjavaagent.ProfilerWithPause.startWithProfilingCommand(ProfilerWithPause.java:257)
at software.amazon.codeguruprofilerjavaagent.ProfilerWithPause.start(ProfilerWithPause.java:202)
at software.amazon.codeguruprofilerjavaagent.ProfilerWithPause.resume(ProfilerWithPause.java:234)
at software.amazon.codeguruprofilerjavaagent.LambdaProfiler.resumeProfiler(LambdaProfiler.java:169)
at software.amazon.codeguruprofilerjavaagent.LambdaProfiler.profile(LambdaProfiler.java:71)
at RequestHandler.handleRequest(RequestHandler.java:243)
... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.management.OperatingSystemMXBean
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 
```

**Comment by brcolow** [comment]
I figured this out. I was running my Lambda with a custom `jlink` JDK and needed to include *both* `java.management` and `jdk.management` modules when creating the JDK with `jlink`. Having a `module-info.java` for the codeguru-java-profiler-agent would alleviate this trial and error.
